apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights
  template:
    metadata:
      labels:
        app: lights
    spec:
      containers:
      - name: my-lights-app
        image: public.ecr.aws/a5z6u3o2/smart-home:lights_5
        ports:
        - containerPort: 80

